# Local Cesium runtime configuration.

ion_access_token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJjNWNiODVhZi1lMjRkLTQxMWEtOGUwOC00NzljMjJhMjkxZTYiLCJpZCI6MjQ2OTk4LCJpYXQiOjE3Mjg1MTI1MDd9.R24O2_Qcl0RbryxLDr2WS5r7jkoxJIpdKJmg34N-Z28'

# Example:
# ion_asset_id=1
