#pragma once

#include <QString>
#include <QList>
#include <memory>

namespace domain {

// Output generated by evaluating a task
struct DesiredState {
    double targetHeadingDegrees = 0.0;
    double targetAltitudeMeters = 0.0;
    double targetSpeedKnots = 0.0;
};

// Base interface for all Tasks
class ITask {
public:
    virtual ~ITask() = default;
    
    enum class State { NotStarted, Running, Completed, Failed };
    
    virtual State getState() const = 0;
    
    // Evaluate the task geometry and return what the entity should physically do
    virtual DesiredState evaluate(double currentLat, double currentLon, double currentAlt, double currentHeading, double dt) = 0;
};

// Primitive Task: Fly a straight line to a geographic coordinate
class MoveToLocationTask : public ITask {
public:
    MoveToLocationTask(double targetLat, double targetLon, double targetAlt, double targetSpeedKnots);
    
    State getState() const override;
    DesiredState evaluate(double currentLat, double currentLon, double currentAlt, double currentHeading, double dt) override;

private:
    double m_targetLat;
    double m_targetLon;
    double m_targetAlt;
    double m_targetSpeed;
    State m_state = State::NotStarted;
};

// Task Stack manages execution of multiple tasks
class TaskStack {
public:
    void push(std::unique_ptr<ITask> task);
    void pop();
    ITask* top() const;
    bool isEmpty() const;
    
    DesiredState evaluateTop(double currentLat, double currentLon, double currentAlt, double currentHeading, double dt);

private:
    QList<std::unique_ptr<ITask>> m_stack;
};

} // namespace domain

// Legacy struct, kept for backward compatibility with FlightDynamicsEngine during refactor
struct EntityTask {
  QString taskType;
  bool enabled = false;
  QString status = QStringLiteral("Idle");
  double targetHeadingDegrees = 0.0;
  int targetAltitudeMeters = 0;
  double targetSpeedKnots = 0.0;
  double targetLatitude = 0.0;
  double targetLongitude = 0.0;
  QString targetEntityName;
};
